# # Generated by Selenium IDE
# import os
#
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#
#
#
#
# class TestHogwarts:
#
#     # def __init__(self):
#     #     # 元素定位
#     #     self._baidu_css = 'title media-heading'
#
#     def setup_method(self):
#         # browser=os.getenv("browser")
#         #
#         # if browser=="chrome":
#             self.driver = webdriver.Chrome()
#         # elif browser=="firefox":
#         #     self.driver = webdriver.Firefox()
#         # else:
#         #     self.driver = webdriver.Chrome()
#
#
#
#     #     self.vars = {}
#     #
#     # def teardown_method(self, method):
#     #      self.driver.quit()
#
#     def test_search(self):
#         self.driver.get("https://testerhome.com/")
#         self.driver.set_window_size(1880, 1000)
#         time.sleep(2)
#         #隐式等待
#         # self.driver.implicitly_wait(5)
#         #显示等待
#         # WebDriverWait(self.driver,10).until(expected_conditions.element_to_be_clickable)
#         # self.driver.find_element(By.NAME, "q").click()
#         # self.driver.find_element(By.NAME, "q").send_keys("appium")
#         # self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
#         self.driver.find_element_by_link_text("社团").click()
#         time.sleep(2)
#         # 点击求职面试圈
#         self.driver.find_element_by_class_name("team-name").click()
#         time.sleep(2)
#         # 点击成员话题的第一个
#         self.driver.find_element(By.CSS_SELECTOR, ".title.media-heading.title a").click()
#         time.sleep(2)
#         # 点击目录
#         self.driver.find_element(By.CSS_SELECTOR,".btn.btn-default").click()
#         time.sleep(1)
#         # 点击目录下列表
#         self.driver.find_elements(By.CSS_SELECTOR,".toc-item-link")[0].click()
#         self.driver.find_elements(By.CSS_SELECTOR, ".toc-item-link")[3].click()
#
#
#
#
#
# if __name__ == '__main__':
#     pytest.main()
