# Generated by Selenium IDE
import os

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



class TestSearch:
    browser = "reuse"

    def setup_method(self):
        browser = os.getenv("browser", "").lower() if self.browser == "" else self.browser
        print(browser)

        if browser == "phantomjs":
            self.driver = webdriver.PhantomJS()

        elif browser == "firefox":
            self.driver = webdriver.Firefox()
        elif browser == 'headless':
            options = webdriver.ChromeOptions()
            # 使用headless模式
            options.add_argument("--headless")
            options.add_argument("--disable-gpu")
            options.add_argument("--window-size=1280,1696")

            self.driver = webdriver.Chrome(options=options)
        elif browser == 'reuse':
            options = webdriver.ChromeOptions()
            options.debugger_address = "127.0.0.1:9222"
            self.driver = webdriver.Chrome(options=options)


    # def setup_method(self):
    #     self.driver = webdriver.Chrome()
    #
    #     pass
    #     self.vars = {}
    #
    # def teardown_method(self, method):
    #      self.driver.quit()

    # def test_search(self):
    #     # self.driver.get("https://testerhome.com/")
    #     # self.driver.set_window_size(1880, 1000)
    #     time.sleep(3)
    #     # self.driver.find_element(By.NAME, "q").click()
    #     # self.driver.find_element(By.NAME, "q").send_keys("appium")
    #     # self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    #     self.driver.find_element_by_link_text("社团").click()
    #     time.sleep(2)
    #     self.driver.find_element_by_class_name("team-name").click()





    # def test_js(self):
    #     for code in [
    #                  "return document.title",
    #                  'return document.querySelector(".active").className'
    #     ]:
    #         result=self.driver.execute_script(code)
    #         print(result)


    def test_member(self):
        time.sleep(2)
        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#contacts")

        time.sleep(2)
        # self.driver.find_element(By.CSS_SELECTOR,".qjs_add_member button").click()

        self.driver.find_element(By.LINK_TEXT, "添加成员").click()
        # self.driver.find_element(By.CSS_SELECTOR,"a.qui_btn.ww_btn.js_add_member")
        time.sleep(2)
        self.driver.find_element(By.NAME,"username").send_keys("abc")
        self.driver.find_element(By.NAME,"english_name").send_keys("红桃A")
        self.driver.find_element(By.NAME,"acctid").send_keys("413581146")
        self.driver.find_element(By.CSS_SELECTOR,".ww_label.ww_label_Middle input").click()
        self.driver.find_element(By.NAME,"mobile").send_keys("12100001234")
        self.driver.find_element(By.NAME,"ext_tel").send_keys("021-0000231")
        self.driver.find_element(By.NAME,"alias").send_keys("413581146@qq.com")
        self.driver.find_element(By.NAME,"xcx_corp_address").send_keys("上海市奉贤区")
        self.driver.find_element(By.NAME,"position").send_keys("软件测试工程师")
        # self.driver.find_element(By.CSS_SELECTOR,"")
        # self.driver.find_element(By.LINK_TEXT,"保存并继续添加").click()
        self.driver.find_element(By.CSS_SELECTOR,"a.qui_btn.ww_btn.ww_btn_Blue.js_btn_continue").click()










    def teardown_method(self):
        time.sleep(5)
        self.driver.quit()

if __name__ == '__main__':
    pytest.main()




